### ISSUE TITLE
No H1 Heading is provided for the page_A11y_Fabric Notes_Fabric Notes_HeadingsAndLabels 

### ISSUE THREAD

**Issue by shindepra** [microsoft/fabricnotes#34]
[[Check out Accessibility Insights!](https://accessibilityinsights.io/)]- Identify accessibility bugs before check-in and make bug fixing faster and easier.

### GitHub Tags:
#A11yMAS; #A11yTCS; #A11ySev2; #DesktopWeb; #Win11; #WCAG2.4.6; #HeadingsAndLabels #Fabric Notes #CELA P3; #Feature_FabricNotes_Web_APR2024. 

### Environment and OS details:
Windows Edition: - Windows 11 Enterprise (23H2)
OS build: - 22631.3007
Chromium Edge Version: Version 123.0.2420.65 (Official build) dev (64-bit) 

### Repro Steps:

1. Hit the URL: [[Fabric Notes - Simple drawings illustrating the main concepts of Microsoft Fabric](https://microsoft.github.io/fabricnotes/) Fabric Notes page will open. 
3. Tab till the "Fabric Notes" Text and press enter. 
4. Run AI4W heading tool. 
5. Observe that No H1 heading is provided for the page.

### Actual Result:
No H1 heading is provided for the page.

### Expected Result:
While the user can navigate to the main content area through the skip to main content link or using the landmark navigation command providing heading level 1 to indicate the start of the main content would be helpful for screen reader users as it as a standard practice for web pages to at least have one main heading on the page.  

### User Impact:
Screen reader users will be disoriented if the first heading of the page takes them straight away to the footer section instead of the beginning of the main content. 

### Attachment:
<img width="953" alt="image" src="https://github.com/microsoft/fabricnotes/assets/143686145/5de3b111-6751-4bee-b631-4ae433e44f7a">

**Comment by Yash14j** [comment]
GitHub Tags:#Rev:yaja;

**Comment by shindepra** [comment]
Verified the bug in below environment,
URL: [[Fabric Notes - Simple drawings illustrating the main concepts of Microsoft Fabric](https://microsoft.github.io/fabricnotes/)
Windows Edition: - Windows 11 Enterprise (23H2)
OS build: - 22631.3007
Chromium Edge Version: Version 123.0.2420.65 (Official build) dev (64-bit)
Issue is fixed.
